export const BADGES = {
  EXPLORER: {
    id:     'explorer',
    stage:  1,
    xp:     50,
    color:  '#A78BFA',
    emoji:  '🧭',
    lottie: '/badges/explorer.json',
    copy:   'Your journey begins. Welcome, Builder!',
  },
  AI_CURIOUS: {
    id:     'ai_curious',
    stage:  2,
    xp:     100,
    color:  '#60A5FA',
    emoji:  '🧠',
    lottie: '/badges/ai-curious.json',
    copy:   "You've unlocked the next level. You're shortlisted!",
  },
  IDEA_LAUNCHER: {
    id:     'idea_launcher',
    stage:  2,
    xp:     75,
    color:  '#34D399',
    emoji:  '💡',
    lottie: '/badges/idea-launcher.json',
    copy:   'Your idea is in the universe. Let\'s make it real.',
  },
  BUILDER: {
    id:     'builder',
    stage:  3,
    xp:     200,
    color:  '#FFB800',
    emoji:  '⚡',
    lottie: '/badges/builder.json',
    copy:   "You're officially a Super Builder. Let's go!",
  },
  WARRIOR: {
    id:     'warrior',
    stage:  4,
    xp:     150,
    color:  '#FB923C',
    emoji:  '🔥',
    lottie: '/badges/warrior.json',
    copy:   'Level up! Workshop 1 complete.',
  },
  DOMAIN_EXPERT: {
    id:     'domain_expert',
    stage:  4,
    xp:     150,
    color:  '#E879F9',
    emoji:  '🎯',
    lottie: '/badges/domain-expert.json',
    copy:   "You've locked your domain. Now build it.",
  },
  PROTOTYPE_PRO: {
    id:     'prototype_pro',
    stage:  4,
    xp:     200,
    color:  '#818CF8',
    emoji:  '🛠️',
    lottie: '/badges/prototype-pro.json',
    copy:   "You have a prototype. That's real.",
  },
  HACKER: {
    id:     'hacker',
    stage:  5,
    xp:     300,
    color:  '#4ADE80',
    emoji:  '💻',
    lottie: '/badges/hacker.json',
    copy:   "You built something. That's huge.",
  },
  SUPER_BUILDER: {
    id:     'super_builder',
    stage:  5,
    xp:     500,
    color:  '#FFD700',
    emoji:  '🏆',
    lottie: '/badges/super-builder.json',
    copy:   'You did it. You are a Super Builder.',
  },
} as const

export type BadgeId = keyof typeof BADGES
